# Generated by Django 3.0.6 on 2020-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingmodel',
            name='website',
            field=models.CharField(default=None, max_length=50, verbose_name='website'),
            preserve_default=False,
        ),
    ]
