# Generated by Django 3.0.6 on 2020-06-04 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_phishingmodel_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
